import type { Metadata } from "next";
import { Exo_2, Orbitron, VT323 } from "next/font/google";
import "./globals.css";
import MatrixBackground from "@/components/MatrixBackground";

const headingFont = Orbitron({
  variable: "--font-heading",
  subsets: ["latin"],
  display: "swap",
});

const bodyFont = Exo_2({
  variable: "--font-body",
  subsets: ["latin"],
  display: "swap",
});

const monoFont = VT323({
  variable: "--font-mono",
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Speaking Practice",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{ background: "var(--bg-deep)" }}>
      <body
        className={`${headingFont.variable} ${bodyFont.variable} ${monoFont.variable} antialiased`}
        style={{
          color: "var(--text-primary)",
          fontFamily: "var(--font-body)",
        }}
      >
        <MatrixBackground />
        {children}
      </body>
    </html>
  );
}
